# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-14 05:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='reminders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiverid', models.IntegerField()),
                ('remindertime', models.CharField(max_length=50)),
                ('reminder', models.TextField()),
            ],
        ),
    ]
